# Look in the tasks/setup.rb file for the various options that can be
# configured in this Rakefile. The .rake files in the tasks directory
# are where the options are used.

begin
  require 'bones'
  Bones.setup
rescue LoadError
  load 'tasks/setup.rb'
end

ensure_in_path 'lib'
require 'rally_velocity_chart'

task :default => 'spec:run'

PROJ.name = 'rally_velocity_chart'
PROJ.authors = 'FIXME (who is writing this software)'
PROJ.email = 'FIXME (your e-mail)'
PROJ.url = 'FIXME (project homepage)'
PROJ.version = RallyVelocityChart::VERSION
PROJ.rubyforge.name = 'rally_velocity_chart'

PROJ.spec.opts << '--color'

PROJ.gem.dependencies = ['rally_cli']
PROJ.gem.need_tar = false
PROJ.ruby_opts = [] # silence warnings